-- Generated by ~/.dotfiles/setup.sh — NVIDIA environment.
--
-- Omarchy ships default/hypr/nvidia.lua, which sets these same three vars,
-- but gates them behind o.shell_succeeds() (an os.execute call). That check
-- does not fire during Hyprland's config parse on this machine, even though
-- omarchy-hw-nvidia and omarchy-hw-nvidia-gsp both exit 0 from a shell, so
-- the vars never reach launched apps and NVIDIA VA-API decode is lost.
--
-- Setting them explicitly is harmless if Omarchy's own detection starts
-- working again: the values are identical to what nvidia.lua would set on a
-- GSP-capable card.
hl.env("NVD_BACKEND", "direct")
hl.env("LIBVA_DRIVER_NAME", "nvidia")
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
