# Generated by Omarchy from the currently selected theme.
export FZF_DEFAULT_OPTS=" \
--color=bg+:{{ selection }},bg:{{ background }},spinner:{{ accent }},hl:{{ red }} \
--color=fg:{{ foreground }},header:{{ red }},info:{{ magenta }},pointer:{{ accent }} \
--color=marker:{{ blue }},fg+:{{ foreground }},prompt:{{ magenta }},hl+:{{ red }} \
--color=selected-bg:{{ selection }} \
--color=border:{{ muted }},label:{{ foreground }}"
