require("items.widgets.amphetamine")
require("items.display_profile")
require("items.widgets.battery")
require("items.widgets.volume")
require("items.widgets.wifi")
require("items.widgets.cpu")
require("items.widgets.ssd")
require("items.widgets.codexbar")
